const TRANSPORT_COST = 400;
const MASK_UK_COST = 65;
const MASK_GERMANY_COST = 100;
const GLOVES_UK_COST = 100;
const GLOVES_GERMANY_COST = 150;

module.exports = {
  TRANSPORT_COST,
  MASK_UK_COST,
  MASK_GERMANY_COST,
  GLOVES_UK_COST,
  GLOVES_GERMANY_COST,
};
